source 'http://ruby.taobao.org'

gem 'rails', '3.1.0'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3', '1.3.4'
gem 'sqlite3-ruby'
gem 'devise', '2.1.0.rc'
gem "devise_ldap_authenticatable", '0.6.0'
gem 'haml', '3.1.2'
gem 'haml-rails', '0.3.4'
gem 'rails3-generators', '0.17.4'
gem 'cancan', '1.6.5'
gem 'inherited_resources', '1.2.2'
gem 'hpricot', '0.8.4'
gem 'ruby_parser', '2.0.6'
gem 'wicked_pdf', '0.7.2'
gem 'mysql2', '~> 0.3'
gem 'kaminari'
gem 'carrot', '0.8.1'
gem 'hirb', '0.4.5'
gem 'paperclip', '2.3.15'
gem 'rest-client', '1.6.3'
gem 'foreigner', '1.0.3'
gem 'memcache-client', '1.8.5'
gem 'eventmachine', '0.12.10'
gem 'delayed_job', :git => "git://github.com/tyraeltong/delayed_job", :branch => "v2.1"
gem 'bullet', '2.0.1', :group => "development"
gem 'therubyracer'
gem "meta_search", :git => "git://github.com/ernie/meta_search.git"
gem "acts_as_audited", :git => "git://github.com/tyraeltong/acts_as_audited.git"

gem "net-ftp-list"
gem "net-sftp"
gem 'annotate', :git => 'git://github.com/ctran/annotate_models.git', :group => "development"
gem 'mongoid', "~> 2.2"
gem 'bson_ext', "~> 1.3"
gem 'chronic_duration'
gem 'pry', :group => 'development'
gem 'redis', ">= 2.2.2"
gem 'resque', :require => "resque/server"
gem 'resque_mailer'


group :test, :development do
  gem 'test-unit', '2.3.0'
  gem 'rspec-rails', '2.6.1'
  gem 'factory_girl', '2.0.1'
  gem 'factory_girl_rails', '1.1.0'
  gem 'ruby-prof', '0.10.8'
  gem 'spork', '~> 1.0rc'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'launchy'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
end

gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', "< 0.8.3", :require => false
  gem 'resque_spec'
end
