require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::ProjectsController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Project. As you add validations to Admin::Project, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all admin_projects as @admin_projects" do
      project = Admin::Project.create! valid_attributes
      get :index
      assigns(:admin_projects).should eq([project])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_project as @admin_project" do
      project = Admin::Project.create! valid_attributes
      get :show, :id => project.id.to_s
      assigns(:admin_project).should eq(project)
    end
  end

  describe "GET new" do
    it "assigns a new admin_project as @admin_project" do
      get :new
      assigns(:admin_project).should be_a_new(Admin::Project)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_project as @admin_project" do
      project = Admin::Project.create! valid_attributes
      get :edit, :id => project.id.to_s
      assigns(:admin_project).should eq(project)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Project" do
        expect {
          post :create, :admin_project => valid_attributes
        }.to change(Admin::Project, :count).by(1)
      end

      it "assigns a newly created admin_project as @admin_project" do
        post :create, :admin_project => valid_attributes
        assigns(:admin_project).should be_a(Admin::Project)
        assigns(:admin_project).should be_persisted
      end

      it "redirects to the created admin_project" do
        post :create, :admin_project => valid_attributes
        response.should redirect_to(Admin::Project.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_project as @admin_project" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Project.any_instance.stub(:save).and_return(false)
        post :create, :admin_project => {}
        assigns(:admin_project).should be_a_new(Admin::Project)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Project.any_instance.stub(:save).and_return(false)
        post :create, :admin_project => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_project" do
        project = Admin::Project.create! valid_attributes
        # Assuming there are no other admin_projects in the database, this
        # specifies that the Admin::Project created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Project.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => project.id, :admin_project => {'these' => 'params'}
      end

      it "assigns the requested admin_project as @admin_project" do
        project = Admin::Project.create! valid_attributes
        put :update, :id => project.id, :admin_project => valid_attributes
        assigns(:admin_project).should eq(project)
      end

      it "redirects to the admin_project" do
        project = Admin::Project.create! valid_attributes
        put :update, :id => project.id, :admin_project => valid_attributes
        response.should redirect_to(project)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_project as @admin_project" do
        project = Admin::Project.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Project.any_instance.stub(:save).and_return(false)
        put :update, :id => project.id.to_s, :admin_project => {}
        assigns(:admin_project).should eq(project)
      end

      it "re-renders the 'edit' template" do
        project = Admin::Project.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Project.any_instance.stub(:save).and_return(false)
        put :update, :id => project.id.to_s, :admin_project => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_project" do
      project = Admin::Project.create! valid_attributes
      expect {
        delete :destroy, :id => project.id.to_s
      }.to change(Admin::Project, :count).by(-1)
    end

    it "redirects to the admin_projects list" do
      project = Admin::Project.create! valid_attributes
      delete :destroy, :id => project.id.to_s
      response.should redirect_to(admin_projects_url)
    end
  end

end
