require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AutomationScriptsController do

  # This should return the minimal set of attributes required to create a valid
  # AutomationScript. As you add validations to AutomationScript, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all automation_scripts as @automation_scripts" do
      automation_script = AutomationScript.create! valid_attributes
      get :index
      assigns(:automation_scripts).should eq([automation_script])
    end
  end

  describe "GET show" do
    it "assigns the requested automation_script as @automation_script" do
      automation_script = AutomationScript.create! valid_attributes
      get :show, :id => automation_script.id.to_s
      assigns(:automation_script).should eq(automation_script)
    end
  end

  describe "GET new" do
    it "assigns a new automation_script as @automation_script" do
      get :new
      assigns(:automation_script).should be_a_new(AutomationScript)
    end
  end

  describe "GET edit" do
    it "assigns the requested automation_script as @automation_script" do
      automation_script = AutomationScript.create! valid_attributes
      get :edit, :id => automation_script.id.to_s
      assigns(:automation_script).should eq(automation_script)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AutomationScript" do
        expect {
          post :create, :automation_script => valid_attributes
        }.to change(AutomationScript, :count).by(1)
      end

      it "assigns a newly created automation_script as @automation_script" do
        post :create, :automation_script => valid_attributes
        assigns(:automation_script).should be_a(AutomationScript)
        assigns(:automation_script).should be_persisted
      end

      it "redirects to the created automation_script" do
        post :create, :automation_script => valid_attributes
        response.should redirect_to(AutomationScript.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved automation_script as @automation_script" do
        # Trigger the behavior that occurs when invalid params are submitted
        AutomationScript.any_instance.stub(:save).and_return(false)
        post :create, :automation_script => {}
        assigns(:automation_script).should be_a_new(AutomationScript)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AutomationScript.any_instance.stub(:save).and_return(false)
        post :create, :automation_script => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested automation_script" do
        automation_script = AutomationScript.create! valid_attributes
        # Assuming there are no other automation_scripts in the database, this
        # specifies that the AutomationScript created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AutomationScript.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => automation_script.id, :automation_script => {'these' => 'params'}
      end

      it "assigns the requested automation_script as @automation_script" do
        automation_script = AutomationScript.create! valid_attributes
        put :update, :id => automation_script.id, :automation_script => valid_attributes
        assigns(:automation_script).should eq(automation_script)
      end

      it "redirects to the automation_script" do
        automation_script = AutomationScript.create! valid_attributes
        put :update, :id => automation_script.id, :automation_script => valid_attributes
        response.should redirect_to(automation_script)
      end
    end

    describe "with invalid params" do
      it "assigns the automation_script as @automation_script" do
        automation_script = AutomationScript.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AutomationScript.any_instance.stub(:save).and_return(false)
        put :update, :id => automation_script.id.to_s, :automation_script => {}
        assigns(:automation_script).should eq(automation_script)
      end

      it "re-renders the 'edit' template" do
        automation_script = AutomationScript.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AutomationScript.any_instance.stub(:save).and_return(false)
        put :update, :id => automation_script.id.to_s, :automation_script => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested automation_script" do
      automation_script = AutomationScript.create! valid_attributes
      expect {
        delete :destroy, :id => automation_script.id.to_s
      }.to change(AutomationScript, :count).by(-1)
    end

    it "redirects to the automation_scripts list" do
      automation_script = AutomationScript.create! valid_attributes
      delete :destroy, :id => automation_script.id.to_s
      response.should redirect_to(automation_scripts_url)
    end
  end

end
