require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AutomationCasesController do

  # This should return the minimal set of attributes required to create a valid
  # AutomationCase. As you add validations to AutomationCase, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all automation_cases as @automation_cases" do
      automation_case = AutomationCase.create! valid_attributes
      get :index
      assigns(:automation_cases).should eq([automation_case])
    end
  end

  describe "GET show" do
    it "assigns the requested automation_case as @automation_case" do
      automation_case = AutomationCase.create! valid_attributes
      get :show, :id => automation_case.id.to_s
      assigns(:automation_case).should eq(automation_case)
    end
  end

  describe "GET new" do
    it "assigns a new automation_case as @automation_case" do
      get :new
      assigns(:automation_case).should be_a_new(AutomationCase)
    end
  end

  describe "GET edit" do
    it "assigns the requested automation_case as @automation_case" do
      automation_case = AutomationCase.create! valid_attributes
      get :edit, :id => automation_case.id.to_s
      assigns(:automation_case).should eq(automation_case)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AutomationCase" do
        expect {
          post :create, :automation_case => valid_attributes
        }.to change(AutomationCase, :count).by(1)
      end

      it "assigns a newly created automation_case as @automation_case" do
        post :create, :automation_case => valid_attributes
        assigns(:automation_case).should be_a(AutomationCase)
        assigns(:automation_case).should be_persisted
      end

      it "redirects to the created automation_case" do
        post :create, :automation_case => valid_attributes
        response.should redirect_to(AutomationCase.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved automation_case as @automation_case" do
        # Trigger the behavior that occurs when invalid params are submitted
        AutomationCase.any_instance.stub(:save).and_return(false)
        post :create, :automation_case => {}
        assigns(:automation_case).should be_a_new(AutomationCase)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AutomationCase.any_instance.stub(:save).and_return(false)
        post :create, :automation_case => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested automation_case" do
        automation_case = AutomationCase.create! valid_attributes
        # Assuming there are no other automation_cases in the database, this
        # specifies that the AutomationCase created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AutomationCase.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => automation_case.id, :automation_case => {'these' => 'params'}
      end

      it "assigns the requested automation_case as @automation_case" do
        automation_case = AutomationCase.create! valid_attributes
        put :update, :id => automation_case.id, :automation_case => valid_attributes
        assigns(:automation_case).should eq(automation_case)
      end

      it "redirects to the automation_case" do
        automation_case = AutomationCase.create! valid_attributes
        put :update, :id => automation_case.id, :automation_case => valid_attributes
        response.should redirect_to(automation_case)
      end
    end

    describe "with invalid params" do
      it "assigns the automation_case as @automation_case" do
        automation_case = AutomationCase.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AutomationCase.any_instance.stub(:save).and_return(false)
        put :update, :id => automation_case.id.to_s, :automation_case => {}
        assigns(:automation_case).should eq(automation_case)
      end

      it "re-renders the 'edit' template" do
        automation_case = AutomationCase.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AutomationCase.any_instance.stub(:save).and_return(false)
        put :update, :id => automation_case.id.to_s, :automation_case => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested automation_case" do
      automation_case = AutomationCase.create! valid_attributes
      expect {
        delete :destroy, :id => automation_case.id.to_s
      }.to change(AutomationCase, :count).by(-1)
    end

    it "redirects to the automation_cases list" do
      automation_case = AutomationCase.create! valid_attributes
      delete :destroy, :id => automation_case.id.to_s
      response.should redirect_to(automation_cases_url)
    end
  end

end
