require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CiMappingsController do

  # This should return the minimal set of attributes required to create a valid
  # CiMapping. As you add validations to CiMapping, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all ci_mappings as @ci_mappings" do
      ci_mapping = CiMapping.create! valid_attributes
      get :index
      assigns(:ci_mappings).should eq([ci_mapping])
    end
  end

  describe "GET show" do
    it "assigns the requested ci_mapping as @ci_mapping" do
      ci_mapping = CiMapping.create! valid_attributes
      get :show, :id => ci_mapping.id.to_s
      assigns(:ci_mapping).should eq(ci_mapping)
    end
  end

  describe "GET new" do
    it "assigns a new ci_mapping as @ci_mapping" do
      get :new
      assigns(:ci_mapping).should be_a_new(CiMapping)
    end
  end

  describe "GET edit" do
    it "assigns the requested ci_mapping as @ci_mapping" do
      ci_mapping = CiMapping.create! valid_attributes
      get :edit, :id => ci_mapping.id.to_s
      assigns(:ci_mapping).should eq(ci_mapping)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CiMapping" do
        expect {
          post :create, :ci_mapping => valid_attributes
        }.to change(CiMapping, :count).by(1)
      end

      it "assigns a newly created ci_mapping as @ci_mapping" do
        post :create, :ci_mapping => valid_attributes
        assigns(:ci_mapping).should be_a(CiMapping)
        assigns(:ci_mapping).should be_persisted
      end

      it "redirects to the created ci_mapping" do
        post :create, :ci_mapping => valid_attributes
        response.should redirect_to(CiMapping.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ci_mapping as @ci_mapping" do
        # Trigger the behavior that occurs when invalid params are submitted
        CiMapping.any_instance.stub(:save).and_return(false)
        post :create, :ci_mapping => {}
        assigns(:ci_mapping).should be_a_new(CiMapping)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CiMapping.any_instance.stub(:save).and_return(false)
        post :create, :ci_mapping => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ci_mapping" do
        ci_mapping = CiMapping.create! valid_attributes
        # Assuming there are no other ci_mappings in the database, this
        # specifies that the CiMapping created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CiMapping.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => ci_mapping.id, :ci_mapping => {'these' => 'params'}
      end

      it "assigns the requested ci_mapping as @ci_mapping" do
        ci_mapping = CiMapping.create! valid_attributes
        put :update, :id => ci_mapping.id, :ci_mapping => valid_attributes
        assigns(:ci_mapping).should eq(ci_mapping)
      end

      it "redirects to the ci_mapping" do
        ci_mapping = CiMapping.create! valid_attributes
        put :update, :id => ci_mapping.id, :ci_mapping => valid_attributes
        response.should redirect_to(ci_mapping)
      end
    end

    describe "with invalid params" do
      it "assigns the ci_mapping as @ci_mapping" do
        ci_mapping = CiMapping.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CiMapping.any_instance.stub(:save).and_return(false)
        put :update, :id => ci_mapping.id.to_s, :ci_mapping => {}
        assigns(:ci_mapping).should eq(ci_mapping)
      end

      it "re-renders the 'edit' template" do
        ci_mapping = CiMapping.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CiMapping.any_instance.stub(:save).and_return(false)
        put :update, :id => ci_mapping.id.to_s, :ci_mapping => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ci_mapping" do
      ci_mapping = CiMapping.create! valid_attributes
      expect {
        delete :destroy, :id => ci_mapping.id.to_s
      }.to change(CiMapping, :count).by(-1)
    end

    it "redirects to the ci_mappings list" do
      ci_mapping = CiMapping.create! valid_attributes
      delete :destroy, :id => ci_mapping.id.to_s
      response.should redirect_to(ci_mappings_url)
    end
  end

end
