require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MailNotifySettingsController do

  # This should return the minimal set of attributes required to create a valid
  # MailNotifySetting. As you add validations to MailNotifySetting, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all mail_notify_settings as @mail_notify_settings" do
      mail_notify_setting = MailNotifySetting.create! valid_attributes
      get :index
      assigns(:mail_notify_settings).should eq([mail_notify_setting])
    end
  end

  describe "GET show" do
    it "assigns the requested mail_notify_setting as @mail_notify_setting" do
      mail_notify_setting = MailNotifySetting.create! valid_attributes
      get :show, :id => mail_notify_setting.id.to_s
      assigns(:mail_notify_setting).should eq(mail_notify_setting)
    end
  end

  describe "GET new" do
    it "assigns a new mail_notify_setting as @mail_notify_setting" do
      get :new
      assigns(:mail_notify_setting).should be_a_new(MailNotifySetting)
    end
  end

  describe "GET edit" do
    it "assigns the requested mail_notify_setting as @mail_notify_setting" do
      mail_notify_setting = MailNotifySetting.create! valid_attributes
      get :edit, :id => mail_notify_setting.id.to_s
      assigns(:mail_notify_setting).should eq(mail_notify_setting)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MailNotifySetting" do
        expect {
          post :create, :mail_notify_setting => valid_attributes
        }.to change(MailNotifySetting, :count).by(1)
      end

      it "assigns a newly created mail_notify_setting as @mail_notify_setting" do
        post :create, :mail_notify_setting => valid_attributes
        assigns(:mail_notify_setting).should be_a(MailNotifySetting)
        assigns(:mail_notify_setting).should be_persisted
      end

      it "redirects to the created mail_notify_setting" do
        post :create, :mail_notify_setting => valid_attributes
        response.should redirect_to(MailNotifySetting.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mail_notify_setting as @mail_notify_setting" do
        # Trigger the behavior that occurs when invalid params are submitted
        MailNotifySetting.any_instance.stub(:save).and_return(false)
        post :create, :mail_notify_setting => {}
        assigns(:mail_notify_setting).should be_a_new(MailNotifySetting)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MailNotifySetting.any_instance.stub(:save).and_return(false)
        post :create, :mail_notify_setting => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mail_notify_setting" do
        mail_notify_setting = MailNotifySetting.create! valid_attributes
        # Assuming there are no other mail_notify_settings in the database, this
        # specifies that the MailNotifySetting created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MailNotifySetting.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => mail_notify_setting.id, :mail_notify_setting => {'these' => 'params'}
      end

      it "assigns the requested mail_notify_setting as @mail_notify_setting" do
        mail_notify_setting = MailNotifySetting.create! valid_attributes
        put :update, :id => mail_notify_setting.id, :mail_notify_setting => valid_attributes
        assigns(:mail_notify_setting).should eq(mail_notify_setting)
      end

      it "redirects to the mail_notify_setting" do
        mail_notify_setting = MailNotifySetting.create! valid_attributes
        put :update, :id => mail_notify_setting.id, :mail_notify_setting => valid_attributes
        response.should redirect_to(mail_notify_setting)
      end
    end

    describe "with invalid params" do
      it "assigns the mail_notify_setting as @mail_notify_setting" do
        mail_notify_setting = MailNotifySetting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MailNotifySetting.any_instance.stub(:save).and_return(false)
        put :update, :id => mail_notify_setting.id.to_s, :mail_notify_setting => {}
        assigns(:mail_notify_setting).should eq(mail_notify_setting)
      end

      it "re-renders the 'edit' template" do
        mail_notify_setting = MailNotifySetting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MailNotifySetting.any_instance.stub(:save).and_return(false)
        put :update, :id => mail_notify_setting.id.to_s, :mail_notify_setting => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mail_notify_setting" do
      mail_notify_setting = MailNotifySetting.create! valid_attributes
      expect {
        delete :destroy, :id => mail_notify_setting.id.to_s
      }.to change(MailNotifySetting, :count).by(-1)
    end

    it "redirects to the mail_notify_settings list" do
      mail_notify_setting = MailNotifySetting.create! valid_attributes
      delete :destroy, :id => mail_notify_setting.id.to_s
      response.should redirect_to(mail_notify_settings_url)
    end
  end

end
