require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProjectTestPlansController do

  # This should return the minimal set of attributes required to create a valid
  # ProjectTestPlan. As you add validations to ProjectTestPlan, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all project_test_plans as @project_test_plans" do
      project_test_plan = ProjectTestPlan.create! valid_attributes
      get :index
      assigns(:project_test_plans).should eq([project_test_plan])
    end
  end

  describe "GET show" do
    it "assigns the requested project_test_plan as @project_test_plan" do
      project_test_plan = ProjectTestPlan.create! valid_attributes
      get :show, :id => project_test_plan.id.to_s
      assigns(:project_test_plan).should eq(project_test_plan)
    end
  end

  describe "GET new" do
    it "assigns a new project_test_plan as @project_test_plan" do
      get :new
      assigns(:project_test_plan).should be_a_new(ProjectTestPlan)
    end
  end

  describe "GET edit" do
    it "assigns the requested project_test_plan as @project_test_plan" do
      project_test_plan = ProjectTestPlan.create! valid_attributes
      get :edit, :id => project_test_plan.id.to_s
      assigns(:project_test_plan).should eq(project_test_plan)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProjectTestPlan" do
        expect {
          post :create, :project_test_plan => valid_attributes
        }.to change(ProjectTestPlan, :count).by(1)
      end

      it "assigns a newly created project_test_plan as @project_test_plan" do
        post :create, :project_test_plan => valid_attributes
        assigns(:project_test_plan).should be_a(ProjectTestPlan)
        assigns(:project_test_plan).should be_persisted
      end

      it "redirects to the created project_test_plan" do
        post :create, :project_test_plan => valid_attributes
        response.should redirect_to(ProjectTestPlan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved project_test_plan as @project_test_plan" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectTestPlan.any_instance.stub(:save).and_return(false)
        post :create, :project_test_plan => {}
        assigns(:project_test_plan).should be_a_new(ProjectTestPlan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectTestPlan.any_instance.stub(:save).and_return(false)
        post :create, :project_test_plan => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested project_test_plan" do
        project_test_plan = ProjectTestPlan.create! valid_attributes
        # Assuming there are no other project_test_plans in the database, this
        # specifies that the ProjectTestPlan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProjectTestPlan.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => project_test_plan.id, :project_test_plan => {'these' => 'params'}
      end

      it "assigns the requested project_test_plan as @project_test_plan" do
        project_test_plan = ProjectTestPlan.create! valid_attributes
        put :update, :id => project_test_plan.id, :project_test_plan => valid_attributes
        assigns(:project_test_plan).should eq(project_test_plan)
      end

      it "redirects to the project_test_plan" do
        project_test_plan = ProjectTestPlan.create! valid_attributes
        put :update, :id => project_test_plan.id, :project_test_plan => valid_attributes
        response.should redirect_to(project_test_plan)
      end
    end

    describe "with invalid params" do
      it "assigns the project_test_plan as @project_test_plan" do
        project_test_plan = ProjectTestPlan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectTestPlan.any_instance.stub(:save).and_return(false)
        put :update, :id => project_test_plan.id.to_s, :project_test_plan => {}
        assigns(:project_test_plan).should eq(project_test_plan)
      end

      it "re-renders the 'edit' template" do
        project_test_plan = ProjectTestPlan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectTestPlan.any_instance.stub(:save).and_return(false)
        put :update, :id => project_test_plan.id.to_s, :project_test_plan => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested project_test_plan" do
      project_test_plan = ProjectTestPlan.create! valid_attributes
      expect {
        delete :destroy, :id => project_test_plan.id.to_s
      }.to change(ProjectTestPlan, :count).by(-1)
    end

    it "redirects to the project_test_plans list" do
      project_test_plan = ProjectTestPlan.create! valid_attributes
      delete :destroy, :id => project_test_plan.id.to_s
      response.should redirect_to(project_test_plans_url)
    end
  end

end
