require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ScreenShotsController do

  # This should return the minimal set of attributes required to create a valid
  # ScreenShot. As you add validations to ScreenShot, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all screen_shots as @screen_shots" do
      screen_shot = ScreenShot.create! valid_attributes
      get :index
      assigns(:screen_shots).should eq([screen_shot])
    end
  end

  describe "GET show" do
    it "assigns the requested screen_shot as @screen_shot" do
      screen_shot = ScreenShot.create! valid_attributes
      get :show, :id => screen_shot.id.to_s
      assigns(:screen_shot).should eq(screen_shot)
    end
  end

  describe "GET new" do
    it "assigns a new screen_shot as @screen_shot" do
      get :new
      assigns(:screen_shot).should be_a_new(ScreenShot)
    end
  end

  describe "GET edit" do
    it "assigns the requested screen_shot as @screen_shot" do
      screen_shot = ScreenShot.create! valid_attributes
      get :edit, :id => screen_shot.id.to_s
      assigns(:screen_shot).should eq(screen_shot)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ScreenShot" do
        expect {
          post :create, :screen_shot => valid_attributes
        }.to change(ScreenShot, :count).by(1)
      end

      it "assigns a newly created screen_shot as @screen_shot" do
        post :create, :screen_shot => valid_attributes
        assigns(:screen_shot).should be_a(ScreenShot)
        assigns(:screen_shot).should be_persisted
      end

      it "redirects to the created screen_shot" do
        post :create, :screen_shot => valid_attributes
        response.should redirect_to(ScreenShot.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved screen_shot as @screen_shot" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScreenShot.any_instance.stub(:save).and_return(false)
        post :create, :screen_shot => {}
        assigns(:screen_shot).should be_a_new(ScreenShot)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScreenShot.any_instance.stub(:save).and_return(false)
        post :create, :screen_shot => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested screen_shot" do
        screen_shot = ScreenShot.create! valid_attributes
        # Assuming there are no other screen_shots in the database, this
        # specifies that the ScreenShot created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ScreenShot.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => screen_shot.id, :screen_shot => {'these' => 'params'}
      end

      it "assigns the requested screen_shot as @screen_shot" do
        screen_shot = ScreenShot.create! valid_attributes
        put :update, :id => screen_shot.id, :screen_shot => valid_attributes
        assigns(:screen_shot).should eq(screen_shot)
      end

      it "redirects to the screen_shot" do
        screen_shot = ScreenShot.create! valid_attributes
        put :update, :id => screen_shot.id, :screen_shot => valid_attributes
        response.should redirect_to(screen_shot)
      end
    end

    describe "with invalid params" do
      it "assigns the screen_shot as @screen_shot" do
        screen_shot = ScreenShot.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScreenShot.any_instance.stub(:save).and_return(false)
        put :update, :id => screen_shot.id.to_s, :screen_shot => {}
        assigns(:screen_shot).should eq(screen_shot)
      end

      it "re-renders the 'edit' template" do
        screen_shot = ScreenShot.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScreenShot.any_instance.stub(:save).and_return(false)
        put :update, :id => screen_shot.id.to_s, :screen_shot => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested screen_shot" do
      screen_shot = ScreenShot.create! valid_attributes
      expect {
        delete :destroy, :id => screen_shot.id.to_s
      }.to change(ScreenShot, :count).by(-1)
    end

    it "redirects to the screen_shots list" do
      screen_shot = ScreenShot.create! valid_attributes
      delete :destroy, :id => screen_shot.id.to_s
      response.should redirect_to(screen_shots_url)
    end
  end

end
