#!/bin/bash
# This a shell script. Run it directly.

QUEUE=marquee_farm rake environment resque:work &
QUEUES=marquee_mailer,marquee_data_sync rake environment resque:work &
#QUEUE=test_resque rake environment resque:work &
