development:
  host: localhost
  database: marquee_web_main_development
  databases:
    marquee_remote_host:
      database: marquee_log
      host: 10.107.100.130
test:
  host: localhost
  database: marquee_web_main_test
  databases:
    marquee_remote_host:
      database: marquee_log
      host: 10.107.100.130
# set these environment variables on your prod server
production:
  host: 10.107.100.114
  database: marquee_web_main_production
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
  databases:
    marquee_remote_host:
      database: marquee_log
      host: 10.107.100.130
